language: ruby
rvm:
- 2.4.1
dist: trusty
sudo: required
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_a17f0d27e567_key -iv $encrypted_a17f0d27e567_iv -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
before_script:
  - psql -c 'create database owdashboard_test;' -U postgres
deploy:
  provider: script
  script: deploy.sh
  on: master
script: bundle exec rspec
