version: 2
jobs:
  build:
    docker:
        - image: circleci/ruby-2.5:node
    steps:
      - checkout
      - get_ruby_deps:
          name: Ruby deps
          command: bundle install
      - test:
          name: run_tests
          command: bundle exec rspec
      - get_nodejs_deps:
          name: Get Node.js deps
          command: yarn install
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: bash .circleci/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci
