version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          DATABASE_USER: root
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: owdashboard_test
    steps:
      - checkout
      - run: bundle
      - run: bundle exec rspec
