version: 2
jobs:
  build:
    docker:
        - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run: bundle
      - run: bundle exec rspec
      - run: yarn install
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: bash .circleci/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci
